baseurl = "/"
theme = "beautifulhugo"
author = "Yung Sung"
title = "Yung Sung"
tags = ["python"]
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[params]
subtitle = "知其然，知其所以然"

[Author]
email = "sunyu418@gmail.com"
github = "syfun"

[[menu.main]]
name = "Blog"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags"
weight = 3